server:
  port: 9191
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: http://localhost:9090
        predicates:
        - Path=/employee-service/profile/**
        - Header=X-CLIENT-NAME,ALTIMETRIK
        filters:
        - name: SetStatus
          args:
            status: 200